# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoneotp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ephoneotp.proto\x12\x08phoneotp\"&\n\x0eSendOTPRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"\"\n\x0fSendOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x10VerifyOTPRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"4\n\x11VerifyOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\x9b\x01\n\x0fPhoneOTPService\x12@\n\x07SendOTP\x12\x18.phoneotp.SendOTPRequest\x1a\x19.phoneotp.SendOTPResponse\"\x00\x12\x46\n\tVerifyOTP\x12\x1a.phoneotp.VerifyOTPRequest\x1a\x1b.phoneotp.VerifyOTPResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phoneotp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDOTPREQUEST._serialized_start=28
  _SENDOTPREQUEST._serialized_end=66
  _SENDOTPRESPONSE._serialized_start=68
  _SENDOTPRESPONSE._serialized_end=102
  _VERIFYOTPREQUEST._serialized_start=104
  _VERIFYOTPREQUEST._serialized_end=157
  _VERIFYOTPRESPONSE._serialized_start=159
  _VERIFYOTPRESPONSE._serialized_end=211
  _PHONEOTPSERVICE._serialized_start=214
  _PHONEOTPSERVICE._serialized_end=369
# @@protoc_insertion_point(module_scope)
